In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r'C:\Users\beher\OneDrive\Desktop\NLP\IMDB Dataset.csv')

In [4]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [7]:
dataset=data.copy()

# convert into Lowercase

In [8]:
data['review']=data['review'].str.lower()

In [9]:
data['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [10]:
print(dataset['review'][0][:300])
print('\n')
print(data['review'][0][:300])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Tru


one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. tru

# Remove html tags

In [12]:
data['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [13]:
from bs4 import BeautifulSoup

In [14]:
text = "<h1>Gopal is learning NLP</h1>"

In [17]:
scoup=BeautifulSoup(text,'html.parser')
print(scoup.get_text())

Gopal is learning NLP

In [18]:
from bs4 import BeautifulSoup
text = "<h1>Hello</h1><p>World</p>"
soup=BeautifulSoup(text,'html.parser')
print(soup.get_text())

HelloWorld

In [19]:

def remove_html(text):
 
 soup=BeautifulSoup(text,"html.parser")
 return soup.get_text()

In [20]:
print(data['review'][0][:500])
print('-'*50)
print(remove_html(data['review'][0])[:500])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz
--------------------------------------------------
one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname

In [22]:
import warnings
warnings.filterwarnings("ignore")
data['review']=data['review'].apply(remove_html)

# Remove url

In [23]:
import re 

text= "Visit https://www.google.com for more information"

In [25]:
result=re.sub(r'https?://\S+','',text)

In [26]:
result

'Visit  for more information'

In [27]:
text = "Check https://openai.com and https://google.com"
result=re.sub(r'https?://\S+','',text)
print(result)

Check  and

In [28]:
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+','',text)

In [29]:
text= "Visit https://www.google.com for more information"

print(remove_url(text))

Visit  for more information

In [30]:
data['review']=data['review'].apply(remove_url)

In [31]:
data['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [ ]:
data[data['review'].str.contains('http')]

                                                  review sentiment
46053  i agree that this film was spectacular. the wa...  positive

In [35]:
data['review'][:46053]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
46048    oh yes, i admit i have made myself guilty of t...
46049    i had high expectations going into this film, ...
46050    this movie just might make you cooooo. the fil...
46051    to be completely honest,i haven't seen that ma...
46052    this movie is so bad and hellraiser part 1 to ...
Name: review, Length: 46053, dtype: object

In [40]:
data.loc[46053, 'review']

'i agree that this film was spectacular. the way in which jamie foxx captured, not only the impression of ray charles, but the essence of ray charles really made the film. his life made a great story and it is good that it is finally being told. i also found a great interview with jamie foxx about this role by ernie manouse from innerviews on kuht, houston channel 8. the link is http: //video.google.com/ videoplay?docid=-3001837218936089620&q =innerviews+ jamie+foxx&hl=en . i encourage everyone to check it out, as it gives in depth looks into what went into his role and his personal feelings about ray charles. the only problem i might cite with the film is that the shotting style was rather bland at times, but in the end i think it helped make the story more realistic and keep the focus on the person, ray charles, rather than the film ray.'

In [41]:
def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

In [42]:
data['review'] = data['review'].apply(remove_urls)

In [43]:
data[data['review'].str.contains('http')]

                                                  review sentiment
46053  i agree that this film was spectacular. the wa...  positive

In [44]:
remove_urls(data.loc[46053, 'review'])

'i agree that this film was spectacular. the way in which jamie foxx captured, not only the impression of ray charles, but the essence of ray charles really made the film. his life made a great story and it is good that it is finally being told. i also found a great interview with jamie foxx about this role by ernie manouse from innerviews on kuht, houston channel 8. the link is http: //video.google.com/ videoplay?docid=-3001837218936089620&q =innerviews+ jamie+foxx&hl=en . i encourage everyone to check it out, as it gives in depth looks into what went into his role and his personal feelings about ray charles. the only problem i might cite with the film is that the shotting style was rather bland at times, but in the end i think it helped make the story more realistic and keep the focus on the person, ray charles, rather than the film ray.'

In [45]:
data.loc[46053, 'review']

'i agree that this film was spectacular. the way in which jamie foxx captured, not only the impression of ray charles, but the essence of ray charles really made the film. his life made a great story and it is good that it is finally being told. i also found a great interview with jamie foxx about this role by ernie manouse from innerviews on kuht, houston channel 8. the link is http: //video.google.com/ videoplay?docid=-3001837218936089620&q =innerviews+ jamie+foxx&hl=en . i encourage everyone to check it out, as it gives in depth looks into what went into his role and his personal feelings about ray charles. the only problem i might cite with the film is that the shotting style was rather bland at times, but in the end i think it helped make the story more realistic and keep the focus on the person, ray charles, rather than the film ray.'

In [46]:
data[data['review'].str.contains('http', case=False, na=False)].shape

(1, 2)

# Punctuation Removal.

In [47]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [48]:
def remove_punctuation(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [49]:
print(data['review'][0][:500])

print("-"*50)

print(remove_punctuation(data['review'][0])[:500])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname
--------------------------------------------------
one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to th

In [50]:
sample = "Wow!!! I can't believe this movie. It's amazing."

print(remove_punctuation(sample))

Wow I cant believe this movie Its amazing

In [51]:
def remove_punctuation(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [52]:
print(data['review'][0][:500])

print("-" * 50)

print(remove_punctuation(data['review'][0])[:500])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname
--------------------------------------------------
one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to th

In [53]:
data['review']=data['review'].apply(remove_punctuation)

In [54]:
data['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production the filming tech...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

# Chat Word Treatment

In [55]:
chat_words = {
    'u': 'you',
    'r': 'are',
    'ur': 'your',
    'btw': 'by the way',
    'lol': 'laughing out loud',
    'omg': 'oh my god'
}

In [56]:
def chat_conversion(text):
    new_text=[]
    for word in text.split():
        if word in chat_words:
            new_text.append(chat_words[word])
        else:
            new_text.append(word)
    return " ".join(new_text)

In [57]:
print(chat_conversion("omg u r awesome"))

oh my god you are awesome

# Tokenization

In [58]:
from nltk.tokenize import word_tokenize

In [59]:
text="i can't belive this movie!"

In [60]:
print(word_tokenize(text))

['i', 'ca', "n't", 'belive', 'this', 'movie', '!']

In [61]:
def token(text):
    return word_tokenize(text)

In [62]:
data['review']=data['review'].apply(token)

In [64]:
data['review']

0        [one, of, the, other, reviewers, has, mentione...
1        [a, wonderful, little, production, the, filmin...
2        [i, thought, this, was, a, wonderful, way, to,...
3        [basically, theres, a, family, where, a, littl...
4        [petter, matteis, love, in, the, time, of, mon...
                               ...
49995    [i, thought, this, movie, did, a, down, right,...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [i, am, a, catholic, taught, in, parochial, el...
49998    [im, going, to, have, to, disagree, with, the,...
49999    [no, one, expects, the, star, trek, movies, to...
Name: review, Length: 50000, dtype: object

In [65]:
type(data['review'][0])

list

# Remove Stopwords

In [66]:
from nltk.corpus import stopwords

In [67]:
stop_words=set(stopwords.words('english'))

In [68]:
print('the' in stop_words)
print('is' in stop_words)
print('not' in stop_words)

True
True
True

In [70]:
stop_words=set(stopwords.words('english'))
tokens=word_tokenize(dataset['review'][0])

filter_token=[]

for word in tokens:
    if word.lower in stop_words:
        filter_token.append(word)

print(filter_token[:30])

[]

In [72]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

filtered_tokens = []

for word in tokens:
    if word.lower() not in stop_words:
        filtered_tokens.append(word)

print(filtered_tokens[:30])

['One', 'reviewers', 'mentioned', 'watching', '1', 'Oz', 'episode', "'ll", 'hooked', '.', 'right', ',', 'exactly', 'happened', 'me.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'first', 'thing', 'struck', 'Oz', 'brutality', 'unflinching', 'scenes']

In [73]:
type(data['review'][0])

list

In [74]:
data['review'][0][:10]

['one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching']

In [77]:
def remove_stopwords(tokens):
    return [word for word in tokens if word.lower() not  in stop_words]

In [78]:
data['review']=data['review'].apply(remove_stopwords)

In [79]:
data['review'][0][:20]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'youll',
 'hooked',
 'right',
 'exactly',
 'happened',
 'methe',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes']

In [80]:
from nltk.stem import PorterStemmer

In [81]:
ps=PorterStemmer()

In [82]:
print(ps.stem("running"))
print(ps.stem("studies"))
print(ps.stem("playing"))

run
studi
play

In [83]:
tokens = ['running', 'studies', 'playing']

stemmed=[ps.stem(word) for word in tokens]
print(stemmed)

['run', 'studi', 'play']

In [84]:
def stem_words(tokens):
    return [ps.stem(word) for word in tokens]

In [85]:
data['review']=data['review'].apply(stem_words)

In [86]:
from nltk.stem import WordNetLemmatizer

In [87]:
lammatizer=WordNetLemmatizer()

In [90]:
print(ps.stem('studies'))
print(lammatizer.lemmatize('studies'))

print(ps.stem('running'))
print(lammatizer.lemmatize('running'))
print(lammatizer.lemmatize('running', pos='v'))

studi
study
run
running
run

In [88]:
def lemmatizer_words(tokens):
    return [lammatizer.lemmatize(word) for word in tokens]

In [89]:
data['review_lemmatized'] = data['review'].apply(lemmatizer_words)